version: '3'
services:
  terraform:
    container_name: 'terraform'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/terraform
    entrypoint: ash
    tty: true
